project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: "In-class Exercise 2: Spatial Weights"
            href: In-class_Ex/In-class_Ex2/In-class_Ex2-Spatial_Weights.html
          - text: "In-class Exercise 2: GLSA"
            href: In-class_Ex/In-class_Ex2/In-class_Ex2-GLSA.html
          - text: "In-class Exercise 2: EHSA"
            href: In-class_Ex/In-class_Ex2/In-class_Ex2-EHSA.html
      - text: Take-home Exercise
        menu: 
          - text: Take-home Exercise 1
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

